// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func hello() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Minimalist Blog</title><style>\n        body {\n            font-family: Arial, sans-serif;\n            margin: 0;\n            padding: 0;\n            background-color: #f4f4f4;\n        }\n        header {\n            background-color: #333;\n            color: #fff;\n            padding: 1em 0;\n            text-align: center;\n        }\n        main {\n            max-width: 800px;\n            margin: 2em auto;\n            padding: 1em;\n            background-color: #fff;\n            border-radius: 5px;\n            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n        }\n        h1, h2, h3 {\n            color: #333;\n        }\n        p {\n            line-height: 1.6;\n        }\n        footer {\n            text-align: center;\n            padding: 1em 0;\n            color: #777;\n            font-size: 0.8em;\n        }\n        a {\n            color: #3498db;\n            text-decoration: none;\n        }\n        a:hover {\n            text-decoration: underline;\n        }\n    </style></head><body><header><h1>My Minimalist Blog</h1></header><main><article><h2>Blog Post Title</h2><p>Published on <time datetime=\"2024-06-18\">June 18, 2024</time></p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut dolor ac justo feugiat consequat. Suspendisse potenti. Nulla facilisi. Donec nec sollicitudin risus. Nulla venenatis interdum nunc, sit amet faucibus erat faucibus sed.</p></article></main><footer><p>&copy; 2024 My Minimalist Blog</p></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
