package handlers

import (
	"gosurpher/db"
	"gosurpher/models"
	"gosurpher/views"

	"github.com/labstack/echo/v4"
)

func PoissonHandler(c echo.Context) error {

	var b models.Blog = db.Select_blog_by_route("poisson")

	return Render(c, views.Poisson(b))
}

func ExponentialHandler(c echo.Context) error {

	var b models.Blog = db.Select_blog_by_route("exponential")

	return Render(c, views.Exponential(b))
}

func GammaHandler(c echo.Context) error {

	var b models.Blog = db.Select_blog_by_route("gamma")

	return Render(c, views.Gamma(b))
}

/*
func generateBarItems() []opts.BarData {
	items := make([]opts.BarData, 0)
	for i := 0; i < 7; i++ {
		items = append(items, opts.BarData{Value: rand.Intn(300)})
	}
	return items
}

func HypergeometricHandler(c echo.Context) error {

	bar := charts.NewBar()
	// set some global options like Title/Legend/ToolTip or anything else
	bar.SetGlobalOptions(charts.WithTitleOpts(opts.Title{
		Title:    "My first bar chart generated by go-echarts",
		Subtitle: "It's extremely easy to use, right?",
	}))

	// Put data into instance
	bar.SetXAxis([]string{"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"}).
		AddSeries("Category A", generateBarItems()).
		AddSeries("Category B", generateBarItems())

	var b models.Blog = db.Select_blog_by_route("hypergeometric")

	bar_chart := RenderGoEcharts(bar.RenderSnippet())

	return Render(c, views.Hypergeometric(b, bar_chart))

}
*/
